
export const ADD_TODO = 'ADD_TODO'
export const TOGGLE_TODO = 'TOGGLE_TODO'
export const UPDATE_TODO = 'UPDATE_TODO'
export const REMOVE_TODO = 'REMOVE_TODO'
export const SELECT_TODO = 'SELECT_TODO'
export const PLAY_TODO = 'PLAY_TODO'
export const STOP_TODO = 'STOP_TODO'
export const CHANGE_TO_BREAK = 'CHANGE_TO_BREAK'
export const PLAY_BREAK = 'PLAY_BREAK'
export const CHANGE_TO_WORK = 'CHANGE_TO_WORK'
